services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: safezone_Site
    ports:
      - "8678:80"
    networks:
      - safezone_site_network
    restart: always

networks:
  safezone_site_network:
    external: true
